# Generated by Django 6.0.3 on 2026-04-03 17:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code fournisseur')),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('forme_juridique', models.CharField(blank=True, max_length=100, verbose_name='Forme juridique')),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('nis', models.CharField(blank=True, max_length=20, verbose_name='NIS')),
                ('rc', models.CharField(blank=True, max_length=20, verbose_name='RC')),
                ('ai', models.CharField(blank=True, max_length=20, verbose_name='AI')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('wilaya', models.CharField(blank=True, max_length=100, verbose_name='Wilaya')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Personne de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone contact')),
                ('payment_terms', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Délai de paiement (jours)')),
                ('currency', models.CharField(choices=[('DZD', 'Dinar algérien'), ('EUR', 'Euro'), ('USD', 'Dollar américain')], default='DZD', max_length=3, verbose_name='Devise')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Nom de la banque')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Compte bancaire')),
                ('rib', models.CharField(blank=True, max_length=23, verbose_name='RIB')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['raison_sociale'],
                'indexes': [models.Index(fields=['code'], name='suppliers_s_code_d1984e_idx'), models.Index(fields=['raison_sociale'], name='suppliers_s_raison__78c7b4_idx'), models.Index(fields=['is_active'], name='suppliers_s_is_acti_a75d30_idx')],
            },
        ),
    ]
