# Generated by Django 6.0.3 on 2026-04-03 17:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProductStockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12, verbose_name='Quantité en stock')),
                ('weighted_average_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Coût moyen pondéré')),
                ('last_movement_date', models.DateTimeField(blank=True, null=True, verbose_name='Dernier mouvement')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('finished_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balance', to='catalog.finishedproduct')),
            ],
            options={
                'verbose_name': 'Solde stock produit fini',
                'verbose_name_plural': 'Soldes stock produits finis',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialStockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12, verbose_name='Quantité en stock')),
                ('last_movement_date', models.DateTimeField(blank=True, null=True, verbose_name='Dernier mouvement')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('raw_material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balance', to='catalog.rawmaterial')),
            ],
            options={
                'verbose_name': 'Solde stock matière première',
                'verbose_name_plural': 'Soldes stock matières premières',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence ajustement')),
                ('adjustment_type', models.CharField(choices=[('inventory', 'Inventaire'), ('correction', 'Correction'), ('loss', 'Perte'), ('damage', 'Avarie'), ('return', 'Retour')], max_length=20, verbose_name="Type d'ajustement")),
                ('adjustment_date', models.DateField(verbose_name='Date ajustement')),
                ('reason', models.TextField(verbose_name='Motif')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Ajustement de stock',
                'verbose_name_plural': 'Ajustements de stock',
                'ordering': ['-adjustment_date'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_before', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité avant')),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité après')),
                ('remarks', models.TextField(blank=True, verbose_name='Observations')),
                ('finished_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.finishedproduct', verbose_name='Produit fini')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.rawmaterial', verbose_name='Matière première')),
                ('stock_adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.stockadjustment')),
            ],
            options={
                'verbose_name': 'Ligne ajustement stock',
                'verbose_name_plural': 'Lignes ajustement stock',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receipt', 'Réception'), ('consumption', 'Consommation'), ('production', 'Production'), ('delivery', 'Livraison'), ('adjustment', 'Ajustement'), ('opening', "Stock d'ouverture"), ('return', 'Retour'), ('loss', 'Perte')], max_length=20, verbose_name='Type de mouvement')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût unitaire')),
                ('source_document_type', models.CharField(choices=[('supplier_dn', 'BL Fournisseur'), ('production_order', 'Ordre de Production'), ('client_dn', 'BL Client'), ('adjustment', 'Ajustement'), ('opening', "Stock d'ouverture")], max_length=20, verbose_name='Type document source')),
                ('source_document_id', models.PositiveIntegerField(verbose_name='ID document source')),
                ('source_line_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID ligne source')),
                ('movement_date', models.DateField(verbose_name='Date mouvement')),
                ('remarks', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('finished_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.finishedproduct', verbose_name='Produit fini')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.rawmaterial', verbose_name='Matière première')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-movement_date', '-created_at'],
                'indexes': [models.Index(fields=['raw_material', 'movement_date'], name='stock_stock_raw_mat_788f86_idx'), models.Index(fields=['finished_product', 'movement_date'], name='stock_stock_finishe_06fd6b_idx'), models.Index(fields=['source_document_type', 'source_document_id'], name='stock_stock_source__1f8465_idx')],
            },
        ),
    ]
