# Generated by Django 6.1 on 2026-08-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='is_dual_mirror',
            field=models.BooleanField(default=False, editable=False, verbose_name='Mouvement miroir (article à double entrée)'),
        ),
    ]
