# Generated by Django 6.0.3 on 2026-04-03 17:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('forme_juridique', models.CharField(blank=True, max_length=100, verbose_name='Forme juridique')),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('nis', models.CharField(blank=True, max_length=20, verbose_name='NIS')),
                ('rc', models.CharField(blank=True, max_length=20, verbose_name='RC')),
                ('ai', models.CharField(blank=True, max_length=20, verbose_name='AI')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('wilaya', models.CharField(max_length=100, verbose_name='Wilaya')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Nom de la banque')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Compte bancaire')),
                ('rib', models.CharField(blank=True, max_length=23, verbose_name='RIB')),
                ('logo', models.ImageField(blank=True, upload_to='company/', verbose_name='Logo')),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.19'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Taux de TVA')),
                ('fiscal_regime', models.CharField(blank=True, max_length=100, verbose_name='Régime fiscal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informations société',
                'verbose_name_plural': 'Informations société',
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('financial', 'Paramètres financiers'), ('stock', 'Paramètres stock'), ('production', 'Paramètres production'), ('alert', 'Paramètres alertes'), ('document', 'Paramètres documents')], max_length=20, verbose_name='Catégorie')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clé')),
                ('value', models.TextField(verbose_name='Valeur')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre système',
                'verbose_name_plural': 'Paramètres système',
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, verbose_name='Préfixe')),
                ('current_year', models.IntegerField(verbose_name='Année courante')),
                ('current_number', models.IntegerField(default=0, verbose_name='Numéro courant')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Séquence document',
                'verbose_name_plural': 'Séquences documents',
                'unique_together': {('prefix', 'current_year')},
            },
        ),
    ]
