# Generated by Django 6.1 on 2026-08-06 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID entité')),
                ('fichier', models.FileField(upload_to='pieces_jointes/%Y/%m/', verbose_name='Fichier (PDF/JPG/PNG)')),
                ('type_document', models.CharField(choices=[('SD-DNF', 'BL Fournisseur signé'), ('SD-INV-F', 'Facture fournisseur originale'), ('SD-PAY-F', 'Justificatif paiement fournisseur'), ('SD-DNC', 'BL Client signé'), ('SD-INV-C', 'Facture client émise'), ('SD-PAY-C', 'Justificatif encaissement client'), ('SD-EXP', 'Justificatif dépense'), ('SD-CORR', 'Document de correction'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type de document')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='contenttypes.contenttype', verbose_name="Type d'entité")),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_jointes_ajoutees', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_piecej_content_783ad4_idx')],
            },
        ),
    ]
