# Generated by Django 6.1 on 2026-08-23 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_piecejointe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsequence',
            name='prefix',
            field=models.CharField(max_length=20, verbose_name='Préfixe'),
        ),
        migrations.CreateModel(
            name='ProductionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du site')),
                ('code', models.CharField(help_text='Code court et unique, intégré aux références de documents (ex : MAIN, EST, OUEST).', max_length=10, unique=True, verbose_name='Code')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, help_text='Magasinier, Responsable Production ou Administrateur référent pour ce site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_sites_en_charge', to=settings.AUTH_USER_MODEL, verbose_name='Contact du site')),
            ],
            options={
                'verbose_name': 'Site de production',
                'verbose_name_plural': 'Sites de production',
                'ordering': ['name'],
            },
        ),
    ]
