# Generated by Django 6.0.3 on 2026-04-03 17:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_ops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence dépense')),
                ('expense_date', models.DateField(verbose_name='Date de la dépense')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('beneficiary', models.CharField(max_length=200, verbose_name='Bénéficiaire')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Espèces'), ('transfer', 'Virement'), ('cheque', 'Chèque'), ('card', 'Carte bancaire'), ('direct_debit', 'Prélèvement')], max_length=20, verbose_name='Mode de paiement')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('status', models.CharField(choices=[('recorded', 'Enregistrée'), ('validated', 'Validée'), ('paid', 'Payée'), ('rejected', 'Rejetée')], default='recorded', max_length=20, verbose_name='Statut')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('linked_supplier_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_ops.supplierinvoice', verbose_name='Facture fournisseur liée')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Validé/Rejeté par')),
                ('category', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='expenses.expensecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-expense_date', '-reference'],
                'indexes': [models.Index(fields=['reference'], name='expenses_ex_referen_46ba13_idx'), models.Index(fields=['category', 'expense_date'], name='expenses_ex_categor_6b4e94_idx'), models.Index(fields=['status'], name='expenses_ex_status_cbb790_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('SD-DNF', 'BL Fournisseur signé'), ('SD-INV-F', 'Facture fournisseur originale'), ('SD-PAY-F', 'Justificatif paiement fournisseur'), ('SD-DNC', 'BL Client signé'), ('SD-INV-C', 'Facture client émise'), ('SD-PAY-C', 'Justificatif encaissement client'), ('SD-EXP', 'Justificatif dépense'), ('SD-CORR', 'Document de correction')], max_length=10, verbose_name='Type de document')),
                ('entity_type', models.CharField(max_length=50, verbose_name="Type d'entité")),
                ('entity_id', models.PositiveIntegerField(verbose_name='ID entité')),
                ('description', models.TextField(verbose_name='Description')),
                ('file_reference', models.CharField(blank=True, max_length=200, verbose_name='Référence fichier')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Document justificatif',
                'verbose_name_plural': 'Documents justificatifs',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='expenses_su_entity__96e919_idx'), models.Index(fields=['doc_type'], name='expenses_su_doc_typ_a13450_idx')],
            },
        ),
    ]
