# Generated by Django 6.0.3 on 2026-04-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='supporting_docs/%Y/%m/', verbose_name='Fichier joint'),
        ),
    ]
