# Generated by Django 6.0.3 on 2026-05-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_supportingdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence bancaire'),
        ),
    ]
