# catalog/forms.py
from django import forms
from .models import RawMaterial, FinishedProduct, RawMaterialCategory, UnitOfMeasure


class RawMaterialForm(forms.ModelForm):
    """
    FIXES:
    - Removed 'reference' from fields entirely. It is editable=False on the model
      and is auto-generated by DocumentSequence in model.save(). Accepting it from
      POST data would bypass the immutability guarantee and the sequential counter.
    - Removed the broken count-based preview in __init__ (race-condition-prone and
      wrong format). The reference appears on the detail view after save.
    """

    class Meta:
        model = RawMaterial
        fields = [
            "designation",
            "category",
            "unit_of_measure",
            "default_supplier",
            "reference_price",
            "alert_threshold",
            "stockout_threshold",
            "is_active",
        ]
        widgets = {
            "designation": forms.TextInput(attrs={"size": 60}),
            "reference_price": forms.NumberInput(attrs={"step": "0.01", "min": "0"}),
            "alert_threshold": forms.NumberInput(attrs={"step": "0.001", "min": "0"}),
            "stockout_threshold": forms.NumberInput(
                attrs={"step": "0.001", "min": "0"}
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["category"].queryset = RawMaterialCategory.objects.filter(
            is_active=True
        )
        self.fields["unit_of_measure"].queryset = UnitOfMeasure.objects.filter(
            is_active=True
        )

        # unit_of_measure is immutable once any DN/formulation line references
        # this material (spec S2). Lock the widget for existing referenced materials.
        if self.instance.pk and self.instance._is_referenced():
            self.fields["unit_of_measure"].disabled = True
            self.fields["unit_of_measure"].help_text = (
                "Unité de mesure non modifiable : matière déjà référencée dans un BL ou une formulation."
            )

    def clean(self):
        cleaned_data = super().clean()
        alert_threshold = cleaned_data.get("alert_threshold")
        stockout_threshold = cleaned_data.get("stockout_threshold")

        # Mirror the model-level constraint so the error surfaces on the form field
        if alert_threshold is not None and stockout_threshold is not None:
            if alert_threshold <= stockout_threshold:
                raise forms.ValidationError(
                    "Le seuil d'alerte doit être strictement supérieur au seuil de rupture."
                )

        return cleaned_data


class FinishedProductForm(forms.ModelForm):
    """
    FIXES:
    - Removed 'reference' from fields (same reason as RawMaterialForm).
    - Removed 'source_formulation' — this field does not exist on FinishedProduct
      (it was removed per spec; the link is via Formulation.finished_product FK on
      the production side).
    """

    class Meta:
        model = FinishedProduct
        fields = [
            "designation",
            "sales_unit",
            "reference_selling_price",
            "alert_threshold",
            "is_active",
        ]
        widgets = {
            "designation": forms.TextInput(attrs={"size": 60}),
            "reference_selling_price": forms.NumberInput(
                attrs={"step": "0.01", "min": "0"}
            ),
            "alert_threshold": forms.NumberInput(attrs={"step": "0.001", "min": "0"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["sales_unit"].queryset = UnitOfMeasure.objects.filter(
            is_active=True
        )


class RawMaterialCategoryForm(forms.ModelForm):
    class Meta:
        model = RawMaterialCategory
        fields = ["name", "description", "is_active"]
        widgets = {
            "description": forms.Textarea(attrs={"rows": 3}),
        }
