# catalog/forms.py
from django import forms
from .models import RawMaterial, FinishedProduct, RawMaterialCategory, UnitOfMeasure


class RawMaterialForm(forms.ModelForm):
    """
    FIXES:
    - Removed 'reference' from fields entirely. It is editable=False on the model
      and is auto-generated by DocumentSequence in model.save(). Accepting it from
      POST data would bypass the immutability guarantee and the sequential counter.
    - Removed the broken count-based preview in __init__ (race-condition-prone and
      wrong format). The reference appears on the detail view after save.

    BR-DUAL-01: a RawMaterial can be made "dual" — mirrored in real time to a
    FinishedProduct row so the same physical article (e.g. a chemical bought
    in bulk that is also resold as-is) is tracked in both the raw-material
    and finished-product catalogues/stocks simultaneously.

    `dual` is a plain (non-model) field:
      - Checking it on a *new* RawMaterial, or on an existing one that isn't
        linked yet, creates a matching FinishedProduct (same designation/
        unit/active) and links it via `twin_finished_product`. No extra
        field is required here — unlike FinishedProductForm's dual toggle,
        FinishedProduct has no category to pick.
      - Unchecking it on an already-linked RawMaterial unlinks it (the
        FinishedProduct catalogue row and its stock history are kept, just
        de-synced going forward).
      - Real-time sync of designation/unit/active, and mirroring of every
        stock movement, is handled by signals (catalog/signals.py,
        stock/signals.py) — this form only manages creating/breaking the
        link itself.

    Pass `user=<User>` from the view so the twin FinishedProduct's
    (required) `created_by` can be filled in.
    """

    dual = forms.BooleanField(
        required=False,
        label="Article à double entrée (matière première + produit fini)",
        help_text="Un produit fini jumeau sera créé/lié, et le stock et la désignation seront synchronisés automatiquement.",
    )

    class Meta:
        model = RawMaterial
        fields = [
            "designation",
            "category",
            "unit_of_measure",
            "default_supplier",
            "reference_price",
            "alert_threshold",
            "stockout_threshold",
            "kg_equivalent_mode",
            "kg_per_unit",
            "density_kg_per_liter",
            "volumetric_factor",
            "row_color",
            "is_active",
        ]
        widgets = {
            "designation": forms.TextInput(attrs={"size": 60}),
            "reference_price": forms.NumberInput(attrs={"step": "0.01", "min": "0"}),
            "alert_threshold": forms.NumberInput(attrs={"step": "0.001", "min": "0"}),
            "stockout_threshold": forms.NumberInput(
                attrs={"step": "0.001", "min": "0"}
            ),
            "kg_per_unit": forms.NumberInput(attrs={"step": "0.0001", "min": "0.0001"}),
            "density_kg_per_liter": forms.NumberInput(
                attrs={"step": "0.0001", "min": "0.0001"}
            ),
            "volumetric_factor": forms.NumberInput(
                attrs={"step": "0.0001", "min": "0.0001"}
            ),
            "row_color": forms.TextInput(attrs={"type": "color"}),
        }

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        self._user = user
        self.fields["category"].queryset = RawMaterialCategory.objects.filter(
            is_active=True
        )
        self.fields["unit_of_measure"].queryset = UnitOfMeasure.objects.filter(
            is_active=True
        )

        # unit_of_measure is immutable once any DN/formulation line references
        # this material (spec S2). Lock the widget for existing referenced materials.
        if self.instance.pk and self.instance._is_referenced():
            self.fields["unit_of_measure"].disabled = True
            self.fields["unit_of_measure"].help_text = (
                "Unité de mesure non modifiable : matière déjà référencée dans un BL ou une formulation."
            )

        self.fields["dual"].initial = bool(
            self.instance and self.instance.pk and self.instance.twin_finished_product_id
        )

    def clean(self):
        cleaned_data = super().clean()
        alert_threshold = cleaned_data.get("alert_threshold")
        stockout_threshold = cleaned_data.get("stockout_threshold")

        # Mirror the model-level constraint so the error surfaces on the form field
        if alert_threshold is not None and stockout_threshold is not None:
            if alert_threshold <= stockout_threshold:
                raise forms.ValidationError(
                    "Le seuil d'alerte doit être strictement supérieur au seuil de rupture."
                )

        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=commit)
        if not commit:
            self.save_m2m = lambda: self._sync_dual(instance)
            return instance
        self._sync_dual(instance)
        return instance

    def _sync_dual(self, instance):
        """Create/link or unlink the twin FinishedProduct per the `dual` checkbox (BR-DUAL-01)."""
        want_dual = self.cleaned_data.get("dual")

        if want_dual and not instance.twin_finished_product_id:
            product = FinishedProduct.objects.create(
                designation=instance.designation,
                sales_unit=instance.unit_of_measure,
                is_active=instance.is_active,
                created_by=self._user or instance.created_by,
            )
            instance.twin_finished_product = product
            instance.save(update_fields=["twin_finished_product"])
        elif not want_dual and instance.twin_finished_product_id:
            instance.twin_finished_product = None
            instance.save(update_fields=["twin_finished_product"])


class FinishedProductForm(forms.ModelForm):
    """
    FIXES:
    - Removed 'reference' from fields (same reason as RawMaterialForm).
    - Removed 'source_formulation' — this field does not exist on FinishedProduct
      (it was removed per spec; the link is via Formulation.finished_product FK on
      the production side).

    BR-DUAL-01 (mirror of RawMaterialForm): a FinishedProduct can be made
    "dual" — mirrored in real time to a RawMaterial row so the same
    physical article is tracked in both catalogues/stocks simultaneously.
    See RawMaterialForm's docstring for the full behaviour. Unlike that
    direction, creating the twin here needs one extra piece of information
    RawMaterial requires that FinishedProduct doesn't have: `category`
    (RawMaterialCategory) — hence `category_twin`.

    Pass `user=<User>` from the view so the twin RawMaterial's (required)
    `created_by` can be filled in.
    """

    dual = forms.BooleanField(
        required=False,
        label="Article à double entrée (produit fini + matière première)",
        help_text="Une matière première jumelle sera créée/liée, et le stock et la désignation seront synchronisés automatiquement.",
    )
    category_twin = forms.ModelChoiceField(
        queryset=None,
        required=False,
        label="Catégorie de la matière première jumelle",
    )

    class Meta:
        model = FinishedProduct
        fields = [
            "designation",
            "sales_unit",
            "reference_selling_price",
            "alert_threshold",
            "kg_equivalent_mode",
            "kg_per_unit",
            "density_kg_per_liter",
            "volumetric_factor",
            "row_color",
            "is_active",
        ]
        widgets = {
            "designation": forms.TextInput(attrs={"size": 60}),
            "reference_selling_price": forms.NumberInput(
                attrs={"step": "0.01", "min": "0"}
            ),
            "alert_threshold": forms.NumberInput(attrs={"step": "0.001", "min": "0"}),
            "kg_per_unit": forms.NumberInput(attrs={"step": "0.0001", "min": "0.0001"}),
            "density_kg_per_liter": forms.NumberInput(
                attrs={"step": "0.0001", "min": "0.0001"}
            ),
            "volumetric_factor": forms.NumberInput(
                attrs={"step": "0.0001", "min": "0.0001"}
            ),
            "row_color": forms.TextInput(attrs={"type": "color"}),
        }
        help_texts = {
            "kg_equivalent_mode": (
                "Non renseigné = 1 unité = 1 kg par défaut (§22)."
            ),
        }

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        self._user = user
        self.fields["sales_unit"].queryset = UnitOfMeasure.objects.filter(
            is_active=True
        )
        self.fields["category_twin"].queryset = RawMaterialCategory.objects.filter(
            is_active=True
        )

        already_dual = bool(
            self.instance and self.instance.pk and hasattr(self.instance, "twin_raw_material")
        )
        self.fields["dual"].initial = already_dual
        if already_dual:
            # Already linked — the twin exists, no need to pick a category again.
            self.fields["category_twin"].widget = forms.HiddenInput()
            self.fields["category_twin"].required = False

    def clean(self):
        cleaned_data = super().clean()
        already_dual = bool(
            self.instance and self.instance.pk and hasattr(self.instance, "twin_raw_material")
        )
        if cleaned_data.get("dual") and not already_dual and not cleaned_data.get("category_twin"):
            self.add_error(
                "category_twin",
                "Requis pour créer la matière première jumelle.",
            )
        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=commit)
        if not commit:
            self.save_m2m = lambda: self._sync_dual(instance)
            return instance
        self._sync_dual(instance)
        return instance

    def _sync_dual(self, instance):
        """Create/link or unlink the twin RawMaterial per the `dual` checkbox (BR-DUAL-01)."""
        already_dual = hasattr(instance, "twin_raw_material")
        want_dual = self.cleaned_data.get("dual")

        if want_dual and not already_dual:
            RawMaterial.objects.create(
                designation=instance.designation,
                category=self.cleaned_data["category_twin"],
                unit_of_measure=instance.sales_unit,
                is_active=instance.is_active,
                twin_finished_product=instance,
                created_by=self._user or instance.created_by,
            )
        elif not want_dual and already_dual:
            RawMaterial.objects.filter(pk=instance.twin_raw_material.pk).update(
                twin_finished_product=None
            )


class RawMaterialCategoryForm(forms.ModelForm):
    class Meta:
        model = RawMaterialCategory
        fields = ["name", "description", "is_active"]
        widgets = {
            "description": forms.Textarea(attrs={"rows": 3}),
        }
