# Generated by Django 6.0.3 on 2026-04-03 17:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, verbose_name='Référence formulation')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('reference_batch_qty', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantité de référence du lot')),
                ('expected_yield_pct', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('200.00'))], verbose_name='Rendement attendu (%)')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('technical_notes', models.TextField(blank=True, verbose_name='Notes techniques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.finishedproduct', verbose_name='Produit fini')),
                ('reference_batch_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unitofmeasure', verbose_name='Unité du lot de référence')),
            ],
            options={
                'verbose_name': 'Formulation',
                'verbose_name_plural': 'Formulations',
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='FormulationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_batch', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantité par lot')),
                ('tolerance_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Tolérance (%)')),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.formulation')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.rawmaterial', verbose_name='Matière première')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unitofmeasure', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Ligne de formulation',
                'verbose_name_plural': 'Lignes de formulation',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence OP')),
                ('formulation_version', models.IntegerField(verbose_name='Version formulation')),
                ('target_qty', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantité cible')),
                ('launch_date', models.DateField(verbose_name='Date de lancement')),
                ('closure_date', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('actual_qty_produced', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Quantité réellement produite')),
                ('stock_check_passed', models.BooleanField(default=False, verbose_name='Vérification stock OK')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='Clôturé par')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.formulation', verbose_name='Formulation')),
                ('target_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unitofmeasure', verbose_name='Unité cible')),
            ],
            options={
                'verbose_name': 'Ordre de Production',
                'verbose_name_plural': 'Ordres de Production',
                'ordering': ['-launch_date', '-reference'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_theoretical', models.DecimalField(decimal_places=3, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Quantité théorique')),
                ('qty_actual', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Quantité réelle')),
                ('tolerance_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Tolérance (%)')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_lines', to='production.productionorder')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.rawmaterial', verbose_name='Matière première')),
            ],
            options={
                'verbose_name': 'Ligne consommation OP',
                'verbose_name_plural': 'Lignes consommation OP',
            },
        ),
        migrations.AddIndex(
            model_name='formulation',
            index=models.Index(fields=['reference'], name='production__referen_430d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='formulation',
            index=models.Index(fields=['finished_product', 'is_active'], name='production__finishe_819b44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formulation',
            unique_together={('reference', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='formulationline',
            unique_together={('formulation', 'raw_material')},
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['reference'], name='production__referen_e1de0b_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['formulation', 'status'], name='production__formula_a5fc18_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['launch_date'], name='production__launch__5b990f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productionorderline',
            unique_together={('production_order', 'raw_material')},
        ),
    ]
