# Generated by Django 6.1 on 2026-08-05 20:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='target_batch_mass_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Masse totale, en kg, du lot de référence — requis si une ligne complément est utilisée (§22).', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Masse cible du lot (kg)'),
        ),
        migrations.AddField(
            model_name='formulationline',
            name='is_complement',
            field=models.BooleanField(default=False, help_text='Quantité calculée automatiquement pour atteindre la masse cible du lot (§22.4).', verbose_name='Complément'),
        ),
    ]
