# Generated by Django 6.1 on 2026-08-12 11:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_formulation_target_batch_mass_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulation',
            name='reference_batch_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('1000.000'), help_text='Production standardisée en kg — 1000 kg par défaut.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantité de référence du lot'),
        ),
    ]
