# Generated by Django 6.1 on 2026-08-12 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_formulation_default_batch_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='corrects_order',
            field=models.ForeignKey(blank=True, help_text="Renseigné uniquement pour un ordre de correction — pointe vers l'OP d'origine.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='production.productionorder', verbose_name="Corrige l'OP"),
        ),
    ]
