# Generated by Django 6.1 on 2026-08-13 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_productionorder_corrects_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='gate_b_ack_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_b_acks', to=settings.AUTH_USER_MODEL, verbose_name='Alerte acquittée par'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='gate_b_ack_note',
            field=models.TextField(blank=True, verbose_name="Note d'acquittement"),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='gate_b_hold',
            field=models.BooleanField(default=False, verbose_name='Alerte QC en cours (Gate B)'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='gate_b_hold_acknowledged',
            field=models.BooleanField(default=False, verbose_name='Alerte Gate B acquittée (BR-QA-07)'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='gate_b_hold_note',
            field=models.TextField(blank=True, verbose_name="Note d'alerte Gate B"),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='scrapped',
            field=models.BooleanField(default=False, help_text="Si vrai, aucun stock PF n'est crédité à la clôture (§6.5).", verbose_name='Rebuté (disposition NCR = Scrap)'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('in_progress', 'En cours'), ('pending_qc_release', 'En attente de libération QC'), ('completed_investigation', 'Terminé — Sous investigation'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=25, verbose_name='Statut'),
        ),
    ]
