# Generated by Django 6.0.3 on 2026-04-03 17:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code client')),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('forme_juridique', models.CharField(blank=True, max_length=100, verbose_name='Forme juridique')),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('nis', models.CharField(blank=True, max_length=20, verbose_name='NIS')),
                ('rc', models.CharField(blank=True, max_length=20, verbose_name='RC')),
                ('ai', models.CharField(blank=True, max_length=20, verbose_name='AI')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('wilaya', models.CharField(blank=True, max_length=100, verbose_name='Wilaya')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Personne de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone contact')),
                ('payment_terms', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Délai de paiement (jours)')),
                ('credit_status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('blocked', 'Bloqué')], default='active', max_length=20, verbose_name='Statut crédit')),
                ('max_discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Remise maximale autorisée (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['raison_sociale'],
                'indexes': [models.Index(fields=['code'], name='clients_cli_code_d90b4a_idx'), models.Index(fields=['raison_sociale'], name='clients_cli_raison__9f3f67_idx'), models.Index(fields=['credit_status'], name='clients_cli_credit__867995_idx'), models.Index(fields=['is_active'], name='clients_cli_is_acti_57c1e7_idx')],
            },
        ),
    ]
