# Generated by Django 6.0.3 on 2026-04-03 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager / Administrateur'), ('stock_prod', 'Responsable Stock/Production'), ('accountant', 'Comptable'), ('sales', 'Commercial'), ('viewer', 'Consultation seule')], max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('action_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('validate', 'Validation'), ('pay', 'Paiement'), ('cancel', 'Annulation'), ('login', 'Connexion'), ('failed_login', 'Échec connexion')], max_length=20, verbose_name="Type d'action")),
                ('module', models.CharField(choices=[('suppliers', 'Fournisseurs'), ('clients', 'Clients'), ('catalog', 'Catalogue'), ('supplier_ops', 'Opérations fournisseurs'), ('production', 'Production'), ('stock', 'Stock'), ('sales', 'Ventes'), ('expenses', 'Dépenses'), ('accounts', 'Comptes'), ('settings_app', 'Paramètres')], max_length=20, verbose_name='Module')),
                ('entity_type', models.CharField(max_length=100, verbose_name="Type d'entité")),
                ('entity_id', models.PositiveIntegerField(verbose_name='ID entité')),
                ('entity_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence entité')),
                ('detail_json', models.TextField(verbose_name='Détails JSON')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'user'], name='accounts_au_timesta_edd478_idx'), models.Index(fields=['module', 'action_type'], name='accounts_au_module_fcbfbd_idx'), models.Index(fields=['entity_type', 'entity_id'], name='accounts_au_entity__473722_idx')],
            },
        ),
    ]
