# Generated by Django 6.1 on 2026-08-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('suppliers', 'Fournisseurs'), ('clients', 'Clients'), ('catalog', 'Catalogue'), ('supplier_ops', 'Opérations fournisseurs'), ('production', 'Production'), ('stock', 'Stock'), ('sales', 'Ventes'), ('expenses', 'Dépenses'), ('accounts', 'Comptes'), ('settings_app', 'Paramètres'), ('quality', 'Qualité / Laboratoire')], max_length=20, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager / Administrateur'), ('stock_prod', 'Responsable Stock/Production'), ('accountant', 'Comptable'), ('sales', 'Commercial'), ('viewer', 'Consultation seule'), ('qa_manager', 'Responsable QA (Assurance Qualité)'), ('qc_technician', 'Technicien QC (Contrôle Qualité)')], max_length=20, verbose_name='Rôle'),
        ),
    ]
