# Generated by Django 6.0.3 on 2026-04-03 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du rapport')),
                ('report_type', models.CharField(choices=[('financial_result', 'Résultat financier'), ('receivables_aging', 'Échéancier clients'), ('payables_aging', 'Échéancier fournisseurs'), ('production_yield', 'Analyse des rendements'), ('expense_breakdown', 'Répartition des dépenses'), ('stock_valuation', 'Valorisation des stocks'), ('sales_analysis', 'Analyse des ventes'), ('supplier_analysis', 'Analyse fournisseurs')], max_length=30, verbose_name='Type de rapport')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('parameters', models.JSONField(default=dict, verbose_name='Paramètres')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Modèle de rapport',
                'verbose_name_plural': 'Modèles de rapports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'exécution")),
                ('status', models.CharField(choices=[('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='running', max_length=20, verbose_name='Statut')),
                ('parameters', models.JSONField(default=dict, verbose_name="Paramètres d'exécution")),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='Données résultat')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Exécuté par')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.reporttemplate', verbose_name='Modèle')),
            ],
            options={
                'verbose_name': 'Exécution de rapport',
                'verbose_name_plural': 'Exécutions de rapports',
                'ordering': ['-execution_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la période')),
                ('period_type', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('annual', 'Annuel'), ('custom', 'Personnalisé')], max_length=20, verbose_name='Type de période')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Période clôturée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Période financière',
                'verbose_name_plural': 'Périodes financières',
                'ordering': ['-start_date'],
                'unique_together': {('period_type', 'start_date', 'end_date')},
            },
        ),
    ]
