# Generated by Django 6.0.3 on 2026-04-03 17:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence facture')),
                ('external_reference', models.CharField(max_length=100, verbose_name='Référence fournisseur')),
                ('invoice_date', models.DateField(verbose_name='Date facture')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('entered', 'Saisie'), ('under_reconciliation', 'En rapprochement'), ('verified', 'Vérifiée'), ('in_dispute', 'En litige'), ('unpaid', 'Impayée'), ('partially_paid', 'Partiellement payée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='entered', max_length=20, verbose_name='Statut')),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total HT')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Montant TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total TTC')),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Solde dû')),
                ('reconciliation_result', models.CharField(choices=[('pending', 'En attente'), ('compliant', 'Conforme'), ('minor_discrepancy', 'Écart mineur'), ('dispute', 'Litige')], default='pending', editable=False, max_length=20, verbose_name='Résultat rapprochement')),
                ('reconciliation_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Écart rapprochement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Facture Fournisseur',
                'verbose_name_plural': 'Factures Fournisseur',
                'ordering': ['-invoice_date', '-reference'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence BL')),
                ('external_reference', models.CharField(max_length=100, verbose_name='Référence fournisseur')),
                ('delivery_date', models.DateField(verbose_name='Date de livraison')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('validated', 'Validé'), ('in_dispute', 'En litige'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('total_amount_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Montant total HT')),
                ('remarks', models.TextField(blank=True, verbose_name='Observations')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Fournisseur')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_supplier_dns', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('linked_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_ops.supplierinvoice', verbose_name='Facture liée')),
            ],
            options={
                'verbose_name': 'BL Fournisseur',
                'verbose_name_plural': 'BL Fournisseurs',
                'ordering': ['-delivery_date', '-reference'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_delivered', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=10)),
                ('price_agreed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('qty_invoiced', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=10)),
                ('price_invoiced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('delta_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=10)),
                ('delta_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('delta_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.rawmaterial')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_lines', to='supplier_ops.supplierinvoice')),
            ],
            options={
                'verbose_name': 'Ligne de rapprochement',
                'verbose_name_plural': 'Lignes de rapprochement',
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceDNLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_dn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_ops.supplierdn')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_ops.supplierinvoice')),
            ],
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='linked_dns',
            field=models.ManyToManyField(through='supplier_ops.SupplierInvoiceDNLink', to='supplier_ops.supplierdn', verbose_name='BL liés'),
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantity_invoiced', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantité facturée')),
                ('unit_price_invoiced', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix unitaire facturé')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.rawmaterial', verbose_name='Matière première')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='supplier_ops.supplierinvoice')),
            ],
            options={
                'verbose_name': 'Ligne Facture Fournisseur',
                'verbose_name_plural': 'Lignes Facture Fournisseur',
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence paiement')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('transfer', 'Virement'), ('cheque', 'Chèque'), ('bill', 'Effet de commerce')], max_length=20, verbose_name='Mode de paiement')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence bancaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Fournisseur')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='supplier_ops.supplierinvoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Paiement Fournisseur',
                'verbose_name_plural': 'Paiements Fournisseur',
                'ordering': ['-payment_date', '-reference'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDNLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantité reçue')),
                ('agreed_unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix unitaire convenu')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.rawmaterial', verbose_name='Matière première')),
                ('supplier_dn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='supplier_ops.supplierdn')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unitofmeasure', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Ligne BL Fournisseur',
                'verbose_name_plural': 'Lignes BL Fournisseur',
                'unique_together': {('supplier_dn', 'raw_material')},
            },
        ),
        migrations.AddIndex(
            model_name='supplierdn',
            index=models.Index(fields=['reference'], name='supplier_op_referen_33c55a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdn',
            index=models.Index(fields=['supplier', 'delivery_date'], name='supplier_op_supplie_356bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdn',
            index=models.Index(fields=['status'], name='supplier_op_status_8a11c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reconciliationline',
            unique_together={('supplier_invoice', 'raw_material')},
        ),
        migrations.AlterUniqueTogether(
            name='supplierinvoicednlink',
            unique_together={('supplier_invoice', 'supplier_dn')},
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['reference'], name='supplier_op_referen_09c469_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['supplier', 'invoice_date'], name='supplier_op_supplie_a7fba7_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['status'], name='supplier_op_status_25bb24_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['due_date'], name='supplier_op_due_dat_18d6bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierinvoiceline',
            unique_together={('supplier_invoice', 'raw_material')},
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['reference'], name='supplier_op_referen_78a9eb_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', 'payment_date'], name='supplier_op_supplie_2885b4_idx'),
        ),
    ]
