# Generated by Django 6.0.3 on 2026-04-25 06:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_ops', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='reconciliation_delta',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='reconciliation_result',
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='status',
            field=models.CharField(choices=[('entered', 'Saisie'), ('verified', 'Vérifiée'), ('in_dispute', 'En litige'), ('unpaid', 'Impayée'), ('partially_paid', 'Partiellement payée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='entered', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='SupplierAccountPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence règlement')),
                ('payment_date', models.DateField(verbose_name='Date de règlement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant réglé')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('transfer', 'Virement'), ('cheque', 'Chèque'), ('bill', 'Effet de commerce')], max_length=20, verbose_name='Mode de paiement')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence bancaire')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_payments', to='suppliers.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Règlement compte fournisseur',
                'verbose_name_plural': 'Règlements compte fournisseur',
                'ordering': ['-payment_date', '-reference'],
            },
        ),
        migrations.DeleteModel(
            name='ReconciliationLine',
        ),
        migrations.AddIndex(
            model_name='supplieraccountpayment',
            index=models.Index(fields=['supplier', 'payment_date'], name='supplier_op_supplie_d4fa9d_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieraccountpayment',
            index=models.Index(fields=['reference'], name='supplier_op_referen_9965c1_idx'),
        ),
    ]
