# Generated by Django 6.0.3 on 2026-05-08 00:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_ops', '0002_remove_supplierinvoice_reconciliation_delta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='payment_method',
            field=models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('espece', 'Espèces'), ('ccp', 'CCP')], default='virement', max_length=20, verbose_name='Mode de règlement'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='timbre_fiscal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Timbre fiscal'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Net à payer'),
        ),
    ]
