# Generated by Django 6.1 on 2026-08-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_ops', '0004_supplierinvoice_is_opening_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierdn',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('pending_qc_sampling', "En attente d'échantillonnage QC"), ('qc_passed', 'QC validé'), ('rejected_returned', 'Rejeté — Retourné au fournisseur'), ('validated', 'Validé'), ('in_dispute', 'En litige'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut'),
        ),
    ]
