# Generated by Django 6.1 on 2026-08-13 18:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_finishedproduct_row_color_rawmaterial_row_color'),
        ('production', '0005_productionorder_gate_b_ack_by_and_more'),
        ('supplier_ops', '0005_alter_supplierdn_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Propriété')),
                ('applies_to', models.CharField(choices=[('raw_material', 'Matière première'), ('finished_product', 'Produit fini'), ('both', 'Les deux')], default='both', max_length=20, verbose_name="S'applique à")),
                ('unit_label', models.CharField(blank=True, help_text='Ex: %, pH, cP, g/cm³, µm, ΔE, °Brix, MPa, CFU/g', max_length=30, verbose_name='Unité')),
                ('test_method_reference', models.CharField(blank=True, max_length=200, verbose_name="Méthode / référence d'essai")),
                ('result_data_type', models.CharField(choices=[('numeric', 'Numérique (valeur unique)'), ('range', 'Numérique (plage min/max)'), ('boolean', 'Booléen (Conforme / Non conforme)'), ('categorical', 'Catégoriel (grade)')], default='numeric', max_length=20, verbose_name='Type de résultat')),
                ('default_precision', models.PositiveSmallIntegerField(default=2, verbose_name='Précision (décimales)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Propriété / Test',
                'verbose_name_plural': 'Catalogue Propriétés / Tests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QualitySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'effet")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_specs_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approuvée par (QA)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_specs_created', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('finished_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_specifications', to='catalog.finishedproduct', verbose_name='Produit fini')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_specifications', to='catalog.rawmaterial', verbose_name='Matière première')),
            ],
            options={
                'verbose_name': 'Spécification qualité',
                'verbose_name_plural': 'Spécifications qualité',
                'ordering': ['-effective_date', '-version'],
                'unique_together': {('raw_material', 'finished_product', 'version')},
            },
        ),
        migrations.CreateModel(
            name='QualitySpecLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_a', models.BooleanField(default=False, verbose_name='Contrôlé à Gate A')),
                ('gate_b', models.BooleanField(default=False, verbose_name='Contrôlé à Gate B')),
                ('gate_c', models.BooleanField(default=False, verbose_name='Contrôlé à Gate C')),
                ('nominal_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Valeur nominale')),
                ('tolerance_pct', models.DecimalField(blank=True, decimal_places=2, help_text='± pourcentage autour de la valeur nominale.', max_digits=6, null=True, verbose_name='Tolérance (%)')),
                ('hard_min', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Min absolu')),
                ('hard_max', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Max absolu')),
                ('is_critical', models.BooleanField(default=False, help_text="Un échec sur cette ligne fait échouer tout l'échantillon.", verbose_name='Critique (BR-QA-05)')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spec_lines', to='quality.property', verbose_name='Propriété')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quality.qualityspecification', verbose_name='Spécification')),
            ],
            options={
                'verbose_name': 'Ligne de spécification',
                'verbose_name_plural': 'Lignes de spécification',
                'unique_together': {('specification', 'property')},
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence échantillon')),
                ('control_point', models.CharField(choices=[('A', 'Gate A — Pré-production (MP entrante)'), ('B', 'Gate B — Mi-production (en cours)'), ('C', 'Gate C — Post-production (PF / rendement)')], max_length=1, verbose_name='Point de contrôle')),
                ('checkpoint_label', models.CharField(blank=True, max_length=100, verbose_name='Point de contrôle (Gate B)')),
                ('quantity_sampled', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Quantité échantillonnée')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('results_pending', 'Résultats en attente'), ('results_recorded', 'Résultats enregistrés'), ('conforming', 'Conforme'), ('non_conforming', 'Non conforme'), ('conditionally_accepted', 'Accepté avec dérogation')], default='draft', max_length=25, verbose_name='Statut')),
                ('sampled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Prélevé le')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_samples', to='production.productionorder', verbose_name='Ordre de production (Gate B/C)')),
                ('quality_specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='quality.qualityspecification', verbose_name='Version de spécification (verrouillée — BR-QA-04)')),
                ('sampled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples_drawn', to=settings.AUTH_USER_MODEL, verbose_name='Prélevé par')),
                ('supplier_dn_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_samples', to='supplier_ops.supplierdnline', verbose_name='Ligne BL fournisseur (Gate A)')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.unitofmeasure', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Échantillon',
                'verbose_name_plural': 'Échantillons',
                'ordering': ['-sampled_at'],
            },
        ),
        migrations.CreateModel(
            name='NonConformityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence NCR')),
                ('gate', models.CharField(choices=[('A', 'Gate A — Pré-production (MP entrante)'), ('B', 'Gate B — Mi-production (en cours)'), ('C', 'Gate C — Post-production (PF / rendement)')], max_length=1, verbose_name='Gate')),
                ('trigger_type', models.CharField(choices=[('failed_sample', 'Échantillon en échec'), ('inprocess_hold', 'Alerte en cours de production (Gate B)'), ('yield_deviation', 'Écart de rendement / consommation'), ('manual', 'Ouverture manuelle')], max_length=20, verbose_name='Type de déclencheur')),
                ('description', models.TextField(verbose_name='Description')),
                ('root_cause_category', models.CharField(blank=True, choices=[('supplier_quality', 'Qualité fournisseur'), ('equipment', 'Équipement'), ('process_operator', 'Process / Opérateur'), ('formula_design', 'Conception formule'), ('measurement_error', 'Erreur de mesure / échantillonnage'), ('environmental', 'Environnemental'), ('other', 'Autre')], max_length=30, verbose_name='Cause racine')),
                ('root_cause_detail', models.TextField(blank=True, verbose_name='Détail cause racine')),
                ('corrective_action', models.TextField(blank=True, verbose_name='Action corrective')),
                ('disposition', models.CharField(blank=True, choices=[('return_to_supplier', 'Retour fournisseur'), ('scrap', 'Mise au rebut'), ('rework', 'Retraitement'), ('accept_deviation', 'Acceptation avec dérogation'), ('accept_no_action', 'Acceptation — aucune action requise')], max_length=25, verbose_name='Disposition')),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('under_review', "En cours d'analyse"), ('dispositioned', 'Dispositionnée'), ('closed', 'Clôturée')], default='open', max_length=15, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ncrs_closed', to=settings.AUTH_USER_MODEL, verbose_name='Clôturée par (QA uniquement — BR-QA-09)')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ncrs_opened', to=settings.AUTH_USER_MODEL, verbose_name='Ouverte par')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ncrs', to='production.productionorder', verbose_name='Ordre de production lié')),
                ('supplier_dn_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ncrs', to='supplier_ops.supplierdnline', verbose_name='Ligne BL fournisseur liée')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ncrs', to='quality.sample', verbose_name='Échantillon lié')),
            ],
            options={
                'verbose_name': 'Non-Conformité (NCR)',
                'verbose_name_plural': 'Non-Conformités (NCR)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SamplingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_point', models.CharField(choices=[('A', 'Gate A — Pré-production (MP entrante)'), ('B', 'Gate B — Mi-production (en cours)'), ('C', 'Gate C — Post-production (PF / rendement)')], max_length=1, verbose_name='Point de contrôle')),
                ('trigger_description', models.CharField(blank=True, help_text='Ex: "par ligne de BL", "après mélange", "par OP terminé"', max_length=200, verbose_name='Déclencheur')),
                ('checkpoint_labels', models.CharField(blank=True, help_text='Libellés séparés par des virgules, ex: Après mélange, Avant conditionnement', max_length=300, verbose_name='Points de contrôle (Gate B)')),
                ('sample_size_rule', models.CharField(blank=True, max_length=200, verbose_name="Règle de taille d'échantillon")),
                ('frequency', models.CharField(choices=[('every', 'À chaque occurrence'), ('every_nth', 'Toutes les N occurrences'), ('statistical', 'Statistique (AQL) — futur')], default='every', max_length=20, verbose_name='Fréquence')),
                ('frequency_n', models.PositiveIntegerField(blank=True, null=True, verbose_name="N (si 'toutes les N occurrences')")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_reason', models.CharField(blank=True, max_length=300, verbose_name='Motif de désactivation (BR-QA-12)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sampling_plans_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('finished_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampling_plans', to='catalog.finishedproduct', verbose_name='Produit fini')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampling_plans', to='catalog.rawmaterial', verbose_name='Matière première')),
            ],
            options={
                'verbose_name': "Plan d'échantillonnage",
                'verbose_name_plural': "Plans d'échantillonnage",
                'ordering': ['control_point', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_value', models.CharField(max_length=200, verbose_name='Valeur relevée')),
                ('recorded_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Valeur numérique (calcul pass/fail)')),
                ('outcome', models.CharField(choices=[('pass', 'Conforme'), ('fail', 'Non conforme')], max_length=10, verbose_name='Résultat calculé')),
                ('instrument_method', models.CharField(blank=True, max_length=200, verbose_name='Instrument / méthode utilisée')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('qa_override', models.BooleanField(default=False, verbose_name='Dérogation QA')),
                ('override_justification', models.TextField(blank=True, verbose_name='Justification de la dérogation')),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_results_overridden', to=settings.AUTH_USER_MODEL, verbose_name='Dérogation accordée par')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_results_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality.sample')),
                ('spec_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_results', to='quality.qualityspecline', verbose_name='Ligne de spécification')),
            ],
            options={
                'verbose_name': 'Résultat de test',
                'verbose_name_plural': 'Résultats de test',
            },
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['control_point', 'status'], name='quality_sam_control_18c7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['reference'], name='quality_sam_referen_ae4953_idx'),
        ),
        migrations.AddIndex(
            model_name='nonconformityreport',
            index=models.Index(fields=['status', 'gate'], name='quality_non_status_ffccf4_idx'),
        ),
        migrations.AddIndex(
            model_name='nonconformityreport',
            index=models.Index(fields=['reference'], name='quality_non_referen_69be51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('sample', 'spec_line')},
        ),
    ]
