# Generated by Django 6.1 on 2026-08-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityspecline',
            name='accepted_categories',
            field=models.CharField(blank=True, help_text='Utilisé si la propriété est de type Catégoriel. Valeurs séparées par des virgules.', max_length=300, verbose_name='Catégories/grades acceptés'),
        ),
        migrations.AddField(
            model_name='qualityspecline',
            name='expected_boolean',
            field=models.BooleanField(blank=True, help_text='Utilisé si la propriété est de type Booléen.', null=True, verbose_name='Résultat attendu (Conforme = coché)'),
        ),
    ]
