# Generated by Django 6.1.1 on 2026-09-06 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rawmaterial_twin_finished_product'),
        ('quality', '0003_dedupe_quality_specification_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qualityspecification',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='qualityspecification',
            constraint=models.UniqueConstraint(condition=models.Q(('finished_product__isnull', True)), fields=('raw_material', 'version'), name='uniq_quality_spec_version_per_raw_material'),
        ),
        migrations.AddConstraint(
            model_name='qualityspecification',
            constraint=models.UniqueConstraint(condition=models.Q(('raw_material__isnull', True)), fields=('finished_product', 'version'), name='uniq_quality_spec_version_per_finished_product'),
        ),
    ]
