# Generated by Django 6.1 on 2026-08-05 20:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='density_kg_per_liter',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Requis si mode = Densité. Unité de mesure doit être volumétrique.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Densité (kg/L)'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='kg_equivalent_mode',
            field=models.CharField(blank=True, choices=[('direct', 'Direct (kg par unité)'), ('density', 'Densité (kg par litre)')], help_text='Méthode de conversion en kg pour les formulations à base de masse (§22).', max_length=10, verbose_name="Mode d'équivalence kg"),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='kg_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Requis si mode = Direct. Masse en kg d'une unité de cette matière.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Kg par unité'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='volumetric_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text="Multiplicateur appliqué à l'équivalent kg pour obtenir le poids volumétrique (§22.6).", max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Facteur volumétrique'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='is_volumetric',
            field=models.BooleanField(default=False, help_text='Coché pour les unités de volume (litre, mL...) — requis pour la conversion par densité.', verbose_name='Unité volumétrique'),
        ),
    ]
