# Generated by Django 6.1 on 2026-08-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_finishedproduct_kg_equivalent'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='row_color',
            field=models.CharField(default='#7c3aed', help_text='Couleur utilisée pour distinguer ce produit fini dans la liste.', max_length=7, verbose_name='Couleur de ligne (catalogue)'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='row_color',
            field=models.CharField(default='#2563eb', help_text='Couleur utilisée pour distinguer cette matière première dans la liste.', max_length=7, verbose_name='Couleur de ligne (catalogue)'),
        ),
    ]
