# Generated by Django 6.1 on 2026-08-22 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_finishedproduct_row_color_rawmaterial_row_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='twin_finished_product',
            field=models.OneToOneField(blank=True, help_text='Lier à un produit fini pour synchroniser automatiquement la quantité et la désignation entre les deux catalogues.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twin_raw_material', to='catalog.finishedproduct', verbose_name='Produit fini jumeau (article à double entrée)'),
        ),
    ]
