# Generated by Django 6.0.3 on 2026-04-03 17:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence facture')),
                ('invoice_date', models.DateField(verbose_name='Date facture')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('issued', 'Émise'), ('partially_paid', 'Partiellement payée'), ('paid', 'Payée'), ('in_dispute', 'En litige'), ('cancelled', 'Annulée')], default='issued', max_length=20, verbose_name='Statut')),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total HT')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Remise (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Montant TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total TTC')),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Solde dû')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Facture Client',
                'verbose_name_plural': 'Factures Client',
                'ordering': ['-invoice_date', '-reference'],
            },
        ),
        migrations.CreateModel(
            name='ClientDN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence BL')),
                ('delivery_date', models.DateField(verbose_name='Date de livraison')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé'), ('delivered', 'Livré'), ('invoiced', 'Facturé'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total HT')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Remise (%)')),
                ('remarks', models.TextField(blank=True, verbose_name='Observations')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_client_dns', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('linked_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.clientinvoice', verbose_name='Facture liée')),
            ],
            options={
                'verbose_name': 'BL Client',
                'verbose_name_plural': 'BL Clients',
                'ordering': ['-delivery_date', '-reference'],
            },
        ),
        migrations.CreateModel(
            name='ClientInvoiceDNLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_dn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.clientdn')),
                ('client_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.clientinvoice')),
            ],
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='linked_dns',
            field=models.ManyToManyField(through='sales.ClientInvoiceDNLink', to='sales.clientdn', verbose_name='BL liés'),
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence encaissement')),
                ('payment_date', models.DateField(verbose_name="Date d'encaissement")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('transfer', 'Virement'), ('cheque', 'Chèque'), ('bill', 'Effet de commerce'), ('card', 'Carte bancaire')], max_length=20, verbose_name='Mode de paiement')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence bancaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Client')),
                ('client_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.clientinvoice', verbose_name='Facture')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Encaissement Client',
                'verbose_name_plural': 'Encaissements Client',
                'ordering': ['-payment_date', '-reference'],
            },
        ),
        migrations.CreateModel(
            name='ClientDNLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delivered', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantité livrée')),
                ('selling_unit_price_ht', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix unitaire HT')),
                ('client_dn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.clientdn')),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.finishedproduct', verbose_name='Produit fini')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.unitofmeasure', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Ligne BL Client',
                'verbose_name_plural': 'Lignes BL Client',
                'unique_together': {('client_dn', 'finished_product')},
            },
        ),
        migrations.AddIndex(
            model_name='clientdn',
            index=models.Index(fields=['reference'], name='sales_clien_referen_875f52_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdn',
            index=models.Index(fields=['client', 'delivery_date'], name='sales_clien_client__753975_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdn',
            index=models.Index(fields=['status'], name='sales_clien_status_eb1d28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientinvoicednlink',
            unique_together={('client_invoice', 'client_dn')},
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['reference'], name='sales_clien_referen_f9a3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['client', 'invoice_date'], name='sales_clien_client__c0805d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['status'], name='sales_clien_status_1cf9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['due_date'], name='sales_clien_due_dat_c88a95_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpayment',
            index=models.Index(fields=['reference'], name='sales_clien_referen_921566_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpayment',
            index=models.Index(fields=['client', 'payment_date'], name='sales_clien_client__f0c50b_idx'),
        ),
    ]
