# Generated by Django 6.0.3 on 2026-05-07 19:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccountPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence règlement')),
                ('payment_date', models.DateField(verbose_name="Date d'encaissement")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant encaissé')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('transfer', 'Virement'), ('cheque', 'Chèque'), ('bill', 'Effet de commerce'), ('card', 'Carte bancaire')], max_length=20, verbose_name='Mode de paiement')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence bancaire')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_payments', to='clients.client', verbose_name='Client')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Règlement compte client',
                'verbose_name_plural': 'Règlements compte client',
                'ordering': ['-payment_date', '-reference'],
                'indexes': [models.Index(fields=['client', 'payment_date'], name='sales_clien_client__a90f9b_idx'), models.Index(fields=['reference'], name='sales_clien_referen_c051ce_idx')],
            },
        ),
    ]
