# Generated by Django 6.1 on 2026-08-06 04:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('sales', '0003_clientinvoice_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinvoice',
            name='is_opening_balance',
            field=models.BooleanField(default=False, verbose_name="Solde d'ouverture (§23 planifié)"),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='clientpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('transfer', 'Virement'), ('cheque', 'Chèque'), ('bill', 'Effet de commerce'), ('card', 'Carte bancaire'), ('advance', 'Avance consommée (§23 planifié)')], max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.CreateModel(
            name='ClientAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence avance')),
                ('origin', models.CharField(choices=[('settlement_surplus', 'Surplus de règlement'), ('direct_entry', 'Saisie directe')], default='direct_entry', max_length=20, verbose_name='Origine')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant (DA)')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant restant (DA)')),
                ('date', models.DateField(verbose_name='Date')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('transfer', 'Virement'), ('cheque', 'Chèque'), ('bill', 'Effet de commerce'), ('card', 'Carte bancaire')], default='cash', help_text='Utilisé seulement pour une saisie directe (origin = Saisie directe).', max_length=20, verbose_name='Mode de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='clients.client', verbose_name='Client')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('settlement', models.OneToOneField(blank=True, help_text='Renseigné uniquement quand origin = Surplus de règlement (§23.4).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advance', to='sales.clientaccountpayment', verbose_name='Règlement source')),
            ],
            options={
                'verbose_name': 'Avance Client (§23 planifié)',
                'verbose_name_plural': 'Avances Client (§23 planifié)',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientAdvanceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant alloué (DA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sales.clientadvance')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_allocations', to='sales.clientinvoice')),
            ],
            options={
                'verbose_name': "Allocation d'avance (§23 planifié)",
                'verbose_name_plural': "Allocations d'avance (§23 planifié)",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientadvance',
            index=models.Index(fields=['client', 'date'], name='sales_clien_client__f615d0_idx'),
        ),
        migrations.AddIndex(
            model_name='clientadvance',
            index=models.Index(fields=['remaining_amount'], name='sales_clien_remaini_ea7414_idx'),
        ),
    ]
